### ISSUE TITLE
NullPointerException W10

### ISSUE THREAD

**Issue by TrickyBoy67** [AurousGroup/aurous.me#7]
Hi,

I'm on W10/64bytes and just installed Aurous but I get this error :

java.lang.NullPointerException
	at me.aurous.updater.DynamicUpdater.addAll(DynamicUpdater.java:58)
	at me.aurous.updater.DynamicUpdater.addAll(DynamicUpdater.java:60)
	at me.aurous.updater.DynamicUpdater.setUpdateDirectory(DynamicUpdater.java:53)
	at me.aurous.updater.BlockingChecker.check(BlockingChecker.java:134)
	at me.aurous.launchwrapper.Updater.main(Updater.java:29)

**Comment by TrickyBoy67** [comment]
Ok after the 3 install and a reebot it worked.
Sorry and great job
